import type { INodeProperties } from 'n8n-workflow';

export const databaseOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['database'] } },
	options: [
		{
			name: 'Add Column',
			value: 'addColumn',
			description: 'Add a new column (field/key) to a database',
			action: 'Add a column to a database',
		},
		{
			name: 'Add Row',
			value: 'addRow',
			description: 'Add a new (detached) row to a database',
			action: 'Add a row to a database',
		},
		{
			name: 'Create',
			value: 'create',
			description: 'Append a new empty database (AttributeView) block to a parent block',
			action: 'Create a database',
		},
		{
			name: 'Get',
			value: 'get',
			description: 'Get the full schema and rows of a database',
			action: 'Get a database',
		},
		{
			name: 'Get Schema',
			value: 'getSchema',
			description: 'Get only the column definitions of a database (no rows)',
			action: 'Get database schema',
		},
		{
			name: 'List',
			value: 'list',
			description: 'List all database (AttributeView) blocks in the workspace',
			action: 'List all databases',
		},
		{
			name: 'Remove Column',
			value: 'removeColumn',
			description: 'Remove a column from a database',
			action: 'Remove a column from a database',
		},
		{
			name: 'Remove Row',
			value: 'removeRow',
			description: 'Remove a row from a database by its row ID',
			action: 'Remove a row from a database',
		},
		{
			name: 'Set Cell',
			value: 'setCell',
			description: 'Set the value of a cell in a database row',
			action: 'Set a cell value in a database',
		},
	],
	default: 'list',
};

export const databaseFields: INodeProperties[] = [
	{
		displayName: 'Parent Block ID',
		name: 'parentBlockId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the parent block (typically a document) to append the new database to',
		displayOptions: { show: { resource: ['database'], operation: ['create'] } },
	},
	{
		displayName: 'AV ID',
		name: 'avId',
		type: 'string',
		required: true,
		default: '',
		description:
			'The AttributeView ID (the data-av-ID attribute of the database block — NOT the block ID itself). Use the List operation to discover existing AV IDs.',
		displayOptions: {
			show: {
				resource: ['database'],
				operation: [
					'get',
					'getSchema',
					'addRow',
					'removeRow',
					'addColumn',
					'removeColumn',
					'setCell',
				],
			},
		},
	},
	{
		displayName: 'Database Block ID',
		name: 'databaseBlockId',
		type: 'string',
		required: true,
		default: '',
		description: 'The block ID of the database (the editor block hosting the AttributeView)',
		displayOptions: { show: { resource: ['database'], operation: ['addRow'] } },
	},
	{
		displayName: 'Primary Key Content',
		name: 'primaryKeyContent',
		type: 'string',
		default: '',
		description: 'The initial content for the primary key cell of the new row',
		displayOptions: { show: { resource: ['database'], operation: ['addRow'] } },
	},
	{
		displayName: 'Row ID',
		name: 'rowId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the row to operate on',
		displayOptions: { show: { resource: ['database'], operation: ['removeRow', 'setCell'] } },
	},
	{
		displayName: 'Column (Key) ID',
		name: 'keyId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the column (key) to operate on',
		displayOptions: {
			show: { resource: ['database'], operation: ['removeColumn', 'setCell'] },
		},
	},
	{
		displayName: 'Column Name',
		name: 'columnName',
		type: 'string',
		required: true,
		default: '',
		description: 'The display name for the new column',
		displayOptions: { show: { resource: ['database'], operation: ['addColumn'] } },
	},
	{
		displayName: 'Column Type',
		name: 'columnType',
		type: 'options',
		required: true,
		default: 'text',
		description: 'The SiYuan column type. Determines how the cell value is stored and rendered.',
		displayOptions: { show: { resource: ['database'], operation: ['addColumn'] } },
		options: [
			{ name: 'Checkbox', value: 'checkbox' },
			{ name: 'Date', value: 'date' },
			{ name: 'Email', value: 'email' },
			{ name: 'Multi-Select', value: 'mSelect' },
			{ name: 'Number', value: 'number' },
			{ name: 'Phone', value: 'phone' },
			{ name: 'Select', value: 'select' },
			{ name: 'Text', value: 'text' },
			{ name: 'URL', value: 'url' },
		],
	},
	{
		displayName: 'Previous Column ID',
		name: 'previousKeyId',
		type: 'string',
		default: '',
		description:
			'Optional. ID of the column the new column should be inserted after. Leave blank to append at the end.',
		displayOptions: { show: { resource: ['database'], operation: ['addColumn'] } },
	},
	{
		displayName: 'Cell Value',
		name: 'cellValue',
		type: 'string',
		default: '',
		description:
			'Value to set. For checkbox use true/false. For multi-select use a comma-separated list. For date use ISO string or epoch ms.',
		displayOptions: { show: { resource: ['database'], operation: ['setCell'] } },
	},
];
